import { Users, Volleyball, Brain } from "lucide-react";
import type { LucideIcon } from "lucide-react";

export interface Player {
  name: string;
  position: string;
  jerseyNumber: number;
  passportImage: string;
  level: number | "Staff";
  registered: boolean;
  isCaptain?: boolean;
}

export interface Team {
  id: string;
  name: string;
  players: Player[];
}

export interface Sport {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  image: string;
  teams: Team[];
}

export const sportsData: Sport[] = [
  {
    id: "football",
    name: "Football",
    description:
      "The beautiful game of strategy, skill, and teamwork on the field.",
    icon: Users,
    image: "/football-match-action.png",
    teams: [
      {
        id: "economics",
        name: "Economics",
        players: [
          {
            name: "TBD",
            position: "Forward",
            jerseyNumber: 9,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
            isCaptain: true,
          },
        ],
      },
      {
        id: "software-eng",
        name: "Software Engineering",
        players: [
          {
            name: "Abdullahi Rabo",
            position: "Goalkeeper",
            jerseyNumber: 1,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: true,
            isCaptain: true,
          },
          {
            name: "Loyalty",
            position: "Goalkeeper",
            jerseyNumber: 2,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Abdullahi A",
            position: "Defender",
            jerseyNumber: 3,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Abdallah Tauhid",
            position: "Midfielder",
            jerseyNumber: 4,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Gibirilla",
            position: "Defender",
            jerseyNumber: 5,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Mafaz",
            position: "Midfielder",
            jerseyNumber: 6,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Musab",
            position: "Forward",
            jerseyNumber: 7,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Najeeb",
            position: "Midfielder",
            jerseyNumber: 8,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Muwaffaq",
            position: "Forward",
            jerseyNumber: 9,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Abdulhadi",
            position: "Midfielder",
            jerseyNumber: 10,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Hayatu",
            position: "Forward",
            jerseyNumber: 11,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Dawud",
            position: "Defender",
            jerseyNumber: 12,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Imran",
            position: "Midfielder",
            jerseyNumber: 13,
            passportImage: "/placeholder-user.jpg",
            level: 300,
            registered: false,
          },
          {
            name: "Muhammad",
            position: "Midfielder",
            jerseyNumber: 14,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Faiz",
            position: "Forward",
            jerseyNumber: 15,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Khalifa",
            position: "Defender",
            jerseyNumber: 16,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Soja",
            position: "Defender",
            jerseyNumber: 17,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Longman",
            position: "Midfielder",
            jerseyNumber: 18,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Nazir",
            position: "Forward",
            jerseyNumber: 19,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Abba Aji",
            position: "Midfielder",
            jerseyNumber: 20,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Destiny Jonah",
            position: "Forward",
            jerseyNumber: 21,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Bulama",
            position: "Defender",
            jerseyNumber: 22,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Santali",
            position: "Midfielder",
            jerseyNumber: 23,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
        ],
      },
      {
        id: "computer-science",
        name: "Computer Science",
        players: [
          {
            name: "Lawal Basiru Dan'isa",
            position: "Forward",
            jerseyNumber: 10,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: true,
          },
          {
            name: "Umar Sani",
            position: "Forward",
            jerseyNumber: 20,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: true,
            isCaptain: true,
          },
          {
            name: "Aboi",
            position: "Defender",
            jerseyNumber: 7,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Khalil",
            position: "Defender",
            jerseyNumber: 66,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Dochiss",
            position: "Defender",
            jerseyNumber: 5,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Abdulbarwa",
            position: "Midfielder",
            jerseyNumber: 88,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Aliyu",
            position: "Goalkeeper",
            jerseyNumber: 1,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Shamsu",
            position: "Forward",
            jerseyNumber: 18,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Samzy",
            position: "Midfielder",
            jerseyNumber: 4,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Sardauna",
            position: "Defender",
            jerseyNumber: 19,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Aminu",
            position: "Central Midfielder",
            jerseyNumber: 21,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Ameer",
            position: "Forward",
            jerseyNumber: 17,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Ahmad",
            position: "Defender",
            jerseyNumber: 89,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Pogba",
            position: "Defender",
            jerseyNumber: 6,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Makama Jr.",
            position: "Midfielder",
            jerseyNumber: 8,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Baeman",
            position: "Midfielder",
            jerseyNumber: 90,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Carreras",
            position: "Defender",
            jerseyNumber: 30,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "M4HM0UD",
            position: "Midfielder",
            jerseyNumber: 77,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
        ],
      },
      {
        id: "bio-tech",
        name: "Bio Technology",
        players: [
          {
            name: "Salim Atiku",
            position: "Midfielder",
            jerseyNumber: 10,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: true,
            isCaptain: true,
          },
          {
            name: "Umar Salihu",
            position: "Midfielder",
            jerseyNumber: 5,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
        ],
      },
      {
        id: "pub-admin",
        name: "Public Administration",
        players: [
          {
            name: "Salim Umar",
            position: "Forward",
            jerseyNumber: 9,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: true,
            isCaptain: true,
          },
          {
            name: "Walid Kolo",
            position: "Midfielder",
            jerseyNumber: 11,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Atom",
            position: "Defender",
            jerseyNumber: 2,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Waliy",
            position: "Midfielder",
            jerseyNumber: 8,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Salim Slimzey",
            position: "Forward",
            jerseyNumber: 10,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Sardauna",
            position: "Defender",
            jerseyNumber: 5,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Tajju",
            position: "Midfielder",
            jerseyNumber: 7,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Jakada",
            position: "Forward",
            jerseyNumber: 19,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Kafarati Hamza",
            position: "Defender",
            jerseyNumber: 4,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Momey",
            position: "Midfielder",
            jerseyNumber: 6,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Al-Amin",
            position: "Defender",
            jerseyNumber: 3,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "BT",
            position: "Midfielder",
            jerseyNumber: 14,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Muddasir",
            position: "Forward",
            jerseyNumber: 17,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Muhammadu Gustavo",
            position: "Midfielder",
            jerseyNumber: 15,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Nasir Bala",
            position: "Defender",
            jerseyNumber: 12,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Deeny",
            position: "Forward",
            jerseyNumber: 20,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Mai Polo",
            position: "Midfielder",
            jerseyNumber: 18,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Mr Nas BIG",
            position: "Defender",
            jerseyNumber: 13,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Bobo",
            position: "Goalkeeper",
            jerseyNumber: 1,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
        ],
      },
      {
        id: "cyber",
        name: "Cyber Security",
        players: [
          {
            name: "David",
            position: "Midfielder",
            jerseyNumber: 10,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: true,
            isCaptain: true,
          },
          {
            name: "Abdulrahman",
            position: "Defender",
            jerseyNumber: 5,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Wesley",
            position: "Forward",
            jerseyNumber: 9,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Anani",
            position: "Midfielder",
            jerseyNumber: 7,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Amanu",
            position: "Defender",
            jerseyNumber: 4,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Khalifa",
            position: "Midfielder",
            jerseyNumber: 8,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Faisal",
            position: "Forward",
            jerseyNumber: 11,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Salim",
            position: "Defender",
            jerseyNumber: 3,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Francis",
            position: "Midfielder",
            jerseyNumber: 6,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Iyal",
            position: "Forward",
            jerseyNumber: 19,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Isreal",
            position: "Defender",
            jerseyNumber: 2,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Suleiman",
            position: "Midfielder",
            jerseyNumber: 14,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Aliyu",
            position: "Defender",
            jerseyNumber: 15,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
          {
            name: "Abubakar",
            position: "Goalkeeper",
            jerseyNumber: 1,
            passportImage: "/placeholder-user.jpg",
            level: 400,
            registered: false,
          },
        ],
      },
      {
        id: "law",
        name: "Law",
        players: [
          {
            name: "Abdulrahman",
            position: "Midfielder",
            jerseyNumber: 10,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: true,
            isCaptain: true,
          },
          {
            name: "Fadil Ahmad",
            position: "Defender",
            jerseyNumber: 5,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Munir Muazu",
            position: "Forward",
            jerseyNumber: 9,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Salisu Nagogo",
            position: "Midfielder",
            jerseyNumber: 7,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Fahad Mande",
            position: "Defender",
            jerseyNumber: 4,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Emmanuel Joshes",
            position: "Forward",
            jerseyNumber: 11,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Usman Hahaha",
            position: "Midfielder",
            jerseyNumber: 8,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Nuhu Ayokanmi",
            position: "Defender",
            jerseyNumber: 3,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Karaye Muhammad",
            position: "Midfielder",
            jerseyNumber: 6,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Abdulgaiz Tallman",
            position: "Forward",
            jerseyNumber: 19,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Haruna Rilwan",
            position: "Defender",
            jerseyNumber: 2,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Abubakar Suleiman Umar",
            position: "Midfielder",
            jerseyNumber: 14,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Abbas George",
            position: "Forward",
            jerseyNumber: 17,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Liman Ahmad",
            position: "Defender",
            jerseyNumber: 15,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Al-Ameen Bolori",
            position: "Midfielder",
            jerseyNumber: 18,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Hahiz",
            position: "Defender",
            jerseyNumber: 12,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Stanley",
            position: "Forward",
            jerseyNumber: 20,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Mustapha",
            position: "Midfielder",
            jerseyNumber: 13,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
          {
            name: "Ammar Muhammad",
            position: "Goalkeeper",
            jerseyNumber: 1,
            passportImage: "/placeholder-user.jpg",
            level: 200,
            registered: false,
          },
        ],
      },
      {
        id: "staff",
        name: "Staff",
        players: [
          {
            name: "Fahad",
            position: "Forward",
            jerseyNumber: 10,
            passportImage: "/placeholder-user.jpg",
            level: "Staff",
            registered: true,
          },
          {
            name: "Adam",
            position: "Midfielder",
            jerseyNumber: 8,
            passportImage: "/placeholder-user.jpg",
            level: "Staff",
            registered: false,
          },
          {
            name: "Mr Ibrahim Labaran",
            position: "Defender",
            jerseyNumber: 5,
            passportImage: "/placeholder-user.jpg",
            level: "Staff",
            registered: false,
            isCaptain: true,
          },
          {
            name: "Mr Khalifa",
            position: "Midfielder",
            jerseyNumber: 7,
            passportImage: "/placeholder-user.jpg",
            level: "Staff",
            registered: false,
          },
          {
            name: "Mr Markus",
            position: "Forward",
            jerseyNumber: 9,
            passportImage: "/placeholder-user.jpg",
            level: "Staff",
            registered: false,
          },
          {
            name: "Mr Jona",
            position: "Defender",
            jerseyNumber: 4,
            passportImage: "/placeholder-user.jpg",
            level: "Staff",
            registered: false,
          },
          {
            name: "Chairman",
            position: "Midfielder",
            jerseyNumber: 6,
            passportImage: "/placeholder-user.jpg",
            level: "Staff",
            registered: false,
          },
          {
            name: "Mr Bello Waziri",
            position: "Defender",
            jerseyNumber: 3,
            passportImage: "/placeholder-user.jpg",
            level: "Staff",
            registered: false,
          },
          {
            name: "Mr Bilal",
            position: "Midfielder",
            jerseyNumber: 11,
            passportImage: "/placeholder-user.jpg",
            level: "Staff",
            registered: false,
          },
        ],
      },
    ],
  },
];
